### ISSUE TITLE
When installing RVC using homebrew using a user with id not 501, it still puts "501" in the JSON config

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-rvc#34]
On macOS, I'm using a user with ID that is not 501. However, `/opt/rvc/etc/rvd.json` is like this:

``` json
{
...
  "user_id": 501,
...
}
```

This means that my RVD pre-auth will always be running under the wrong user. Could we update the installation instructions to give some input to the install script, like this?

```
sudo /usr/local/bin/rvc_install.sh -u $(id)
```

cc: @erikbor @jjr840430

**Comment by erikbor** [comment]
We can make `rvc_install.sh` use the `SUDO_USER` environment variable so a user doesn't have to add the `-u` switch.

**Comment by ronaldtse** [comment]
Agree. Awesome suggestion @erikbor .

**Comment by erikbor** [comment]
Fixed by [222](https://github.com/riboseinc/rvc/pull/222)

**Comment by erikbor** [comment]
Merged.
