### ISSUE TITLE
Update version to 1.0.1

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-rvc#35]
@jjr840430 could you help update the formula to use the 1.0.1 release (and use the actual release and `sha256`)?

Thanks.

**Comment by jjr840430** [comment]
@ronaldtse It was implemented. Please review it. Thanks.

**Comment by ronaldtse** [comment]
Very nice, thanks @jjr840430 ! P.S. next time could you use a PR? We don't want to directly modify master. Thanks!

**Comment by jjr840430** [comment]
ok, I will. Thanks.
