### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/homebrew-rvc#40]
```console
$ brew install rvc
...
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
...
```

as reported by one of the users.

version: v1.1.1

**Comment by erikbor** [comment]
Hi @jjr840430,

I can confirm this bug. Can you please help fix it?

Thanks!

**Comment by jjr840430** [comment]
@erikbor OK, I will check and let you know.

**Comment by erikbor** [comment]
@ribose-jeffreylau @jjr840430 fixed it, I verified it on my side but can you ping the user?

**Comment by ribose-jeffreylau** [comment]
The user confirms that it now installs without error.  Thanks @jjr840430 !
