### ISSUE TITLE
Issue with installation instructions

### ISSUE THREAD

**Issue by PeterTKY** [riboseinc/homebrew-rvc#49]
https://github.com/riboseinc/homebrew-rvc/blob/8de57b4b581ec574ed25c17a2be271fbf1e08fa1/Formula/rvc.rb#L36

This line is:
```
PATH=/opt/rvc/bin:/usr/local/bin
```

And should be:

```
PATH=/opt/rvc/bin:/usr/local/bin:$PATH
```

**Comment by jjr840430** [comment]
@PeterTKY It was fixed [here](https://github.com/riboseinc/homebrew-rvc/pull/51)
